[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
todo_app = "BU8nAiw1qPvbipixuTcF6APc7PP7SYbhZBSVFjvWVf2h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
